SRE-2515: New LICENSE file as expected by OpenSSF Scorecard
daos-stack/mercury pull request #124
Opened 2024-10-02 17:43 UTC by osalyk

Doc-only: true

2024-10-02 19:06 UTC, grom72 submitted a review, later dismissed

2024-10-02 19:30 UTC, daltonbohning submitted a review, later dismissed

2024-10-04 08:28 UTC, janekmi requested changes

2024-10-04 08:28 UTC, janekmi commented on Makefile
> +# Copyright (C) 2019-2024 Intel Corporation
```suggestion
# Copyright (c) 2018-2024 Intel Corporation
```

2024-10-04 08:28 UTC, janekmi commented on LICENSE
> +Copyright 2019-2024 Intel Corporation.
```suggestion
Copyright 2018-2024 Intel Corporation.
```

2024-10-04 09:03 UTC, osalyk commented on Makefile
> +# Copyright (C) 2019-2024 Intel Corporation
Done.

2024-10-04 09:03 UTC, osalyk commented on LICENSE
> +Copyright 2019-2024 Intel Corporation.
Done.

2024-10-04 10:03 UTC, grom72 approved these changes

2024-10-04 10:50 UTC, janekmi approved these changes

2024-10-07 18:10 UTC, merged