DAOS-11467 mercury: Add local address to end point for single IB device.
daos-stack/mercury pull request #87
Opened 2022-09-19 22:04 UTC by jgmoore-or

Fixes bug in na_ucp_connect function.

Signed-off-by: Joseph Moore <joseph.moore@intel.com>

2022-09-19 22:09 UTC, frostedcmos submitted a review, later dismissed

2022-09-19 22:19 UTC, soumagne approved these changes

2022-09-20 13:23 UTC, brianjmurrell requested changes
You need to go through the normal dependency modification process that includes the changelog(s) and `Version` (or) `Release:` bumps so that we are not rebuilding a previously used `Verison`/`Release`.

The changelog entries should indicate the modification to the patch.

2022-09-20 13:39 UTC, jolivier23 approved these changes

2022-09-20 14:23 UTC, soumagne approved these changes

2022-09-20 16:14 UTC, frostedcmos approved these changes

2022-09-20 16:52 UTC, brianjmurrell approved these changes

2022-09-20 19:08 UTC, merged